name: Keep Render awake

on:
  schedule:
    - cron: '*/5 * * * *'    # 5分ごとに実行 (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping render service (with retries)
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          if [ -z "$RENDER_URL" ]; then
            echo "ERROR: RENDER_URL is not set. Set it in Repo Secrets."
            exit 1
          fi

          echo "Pinging $RENDER_URL"
          for i in 1 2 3; do
            echo "Attempt $i..."
            curl --max-time 10 --retry 2 --retry-delay 2 --fail -sS "$RENDER_URL" > /dev/null && { echo "OK"; exit 0; } || echo "failed"
            sleep 2
          done

          echo "All attempts failed."
          exit 1
