name: Generate lockfile
on: [push]

permissions:
  contents: write   # ← GitHub Actions に push 権限を付与

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add package-lock.json
      - run: git commit -m "Add lockfile" || echo "No changes"
      - run: git push
